### ISSUE TITLE
EventSourcing thoughts

### ISSUE THREAD

**Issue by timohayes** [dotnetjunkie/solidservices#15]
Hi  @dotnetjunkie ,
Great job with this project! One question: Have you ever thought about expanding your architecture to include event sourcing? I think it is common practice to include event sourcing with CQRS, and I am curious how you would implement that here, or if you have done that with this stack before? 

Thanks!

**Comment by dotnetjunkie** [comment]
Event Sourcing and CQRS are two architectural styles that can be used independently of each other. Where I find the CQRS-like style of separating queries from commands with the addition of making the architecture message-based highly usable in the majority of applications, event Sourcing is a more specialized pattern which with more architectural consequences. Not all applications benefit from using Event Sourcing. Where commands and queries are often quite easy to introduce on an existing application, that doesn't hold for Event Sourcing.

Because of this I actually don't consider it common practice to mix CQRS with Event Sourcing. This doesn't mean that Event Sourcing isn't useful. On the contrary, I think that for the right type of application it can be tremendously beneficial or even the best approach.

My intention of this sample project is to show case the message-based architecture around commands and queries, and especially to show that this kind of architecture can remove the need for thick service layers like WCF and Web API. From that perspective, it doesn't make sense to add Event Sourcing to this solution.

When it comes to reference architecture projects with Event Sourcing, [The CQRS Kitchen](https://thecqrskitchen.codeplex.com/ ) from @dennisdoomen comes to mind. You might want to take a look at that.

**Comment by timohayes** [comment]
Thanks for sharing your thoughts and for the link, I'll take a look at it.
