### ISSUE TITLE
Authentication with Commands?

### ISSUE THREAD

**Issue by maulwuff** [dotnetjunkie/solidservices#18]
Hi,
in <https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=92> you once wrote:

> ... However, in the case of logging in a user, I don't think that's really suited for a command, since you are really asking a question here (while doing a side effect). Instead, I would use an IAuthorizationService or something like that.

On a WebApi or WCF app, Commands and Queries are the only way to communicate from the Gui to the backend. Is there something else that would fit for the login use case (user has to enter username and password to authenticate, or user has to scan his/her id card to authenticate)?

Talking about passwords: how do you handle sensitive data on commands? Do you encrypt them clientside before transferring them to the server?

**Comment by dotnetjunkie** [comment]
> On a WebApi or WCF app, Commands and Queries are the only way to communicate from the Gui to the backend.

It's completely up to you to add an `AuthenticationController` Web API Controller or an `AuthenticationService` WCF service. Not everything _has_ to go through a command or a query.

> Is there something else that would fit for the login use case (user has to enter username and password to authenticate, or user has to scan his/her id card to authenticate)?

Here are some ideas:

- With SOAP requests, it is quite common to send the username/password with each request as part of the SOAP header.
- You can do the same with Web API where you place username/password in header of each web request. This does typically prevent the API from being used from within a browser though, since there you are dealing with CSRF attacks. Still, this method is useful for server-to-server communication.
- Have a `LoginCommand`. In case of a failed login you return validation errors that indicate the username/password combination is incorrect or the account is locked out. Although a command itself doesn't return data, that doesn't mean that the _web request_ can't. For instance, after a successful login, you will have session information at the server and send the session token through a cookie to the browser. Another option is to let the browser generate the token itself and pass it on through the command.

> Talking about passwords: how do you handle sensitive data on commands? Do you encrypt them client side before transferring them to the server?

Use HTTPS. All your client/server communication should be encrypted using HTTPS. When you've got that in place, there is typically little reason to add message level encryption, except in very rare circumstances.

**Comment by maulwuff** [comment]
Thanks for your help. Great as always :)
