### ISSUE TITLE
Report progress and cancel long running queries

### ISSUE THREAD

**Issue by maulwuff** [dotnetjunkie/solidservices#19]
Have you ever come accross the need to report progress of a query execution? 
I have a long running query which constists of 3 main blocks to execute. As `IQuery` returns a query result when it is finished, I see no possibility to report intermediate results. 

The opposite would be, how to cancel a running query. As I understand it, queries are kind of fire and ~forget~ wait until they are finished. With the possibility to have a contract-serializer sitting somewhere in the pipeline I doubt that using a `CancellationToken` would work?

**Comment by dotnetjunkie** [comment]
Both progress reporting and cancellation are things I haven't needed myself in the applications I write, but the model doesn't permit this per se.

There are several ways to return intermediate results. One thing that comes to mind is that you split up the query in multiple smaller queries and see each query as a percentage of the work.

Another option is to let the query handler depend on some sort of `IProgressReporter` abstraction, that allows the query to communicate its progress to its consumers.

When it comes to cancellation, there are two models that come to mind. The most common model that you see in most examples online is that you make cancellation an _explicit_ concept that is exposed through the abstraction, i.e.:

``` c#
public interface IQueryHandler<TQuery, TResult> where TQuery : IQuery<TResult>
{
    // adds cancellation to the abstraction
    TResult Handle(TQuery query, CancellationToken cancellation); 
}
```

I personally don't like this, since cancellation is (to me) an implementation detail, and it pollutes _all_ your handlers _and_ consumers, while only a few actually need this.

So a more pleasant model is to make cancellation an _implementation detail_. You can do this by injecting some sort of `ICancellationProvider` abstraction into the query handler. That provider can give access to the token that is provided or set by part where the request started:

``` c#
public interface ICancellationProvider
{
    CancellationToken Token { get; }
}
```

I hope this helps.

**Comment by maulwuff** [comment]
Thanks a lot. 
For the first step I used the structure there already was. I split it up into 3 queries. This had the possitive side effect of reducing some of dto complexity I needed to have in there ;-)
