### ISSUE TITLE
[Q] async/await Handlers

### ISSUE THREAD

**Issue by maulwuff** [dotnetjunkie/solidservices#31]
Can you elaborate on your design decisions, why you chose the sync version instead of the async way, please? 
sync:
`TResult Handle(TQuery query);`
async:
`Task<TResult> Handle(TQuery query);`

**Comment by deeproute** [comment]
Hello maulwuff,
From what I understood, the domain (or business layer in this case) is only concerned on domain objects. Its not an async method because that will force the function to return a Task<T> result which is considered a leaky abstraction. If you want to go fully deep in the subject I highly recommend you see this talk by Mark Seeman which explains this in more detail:
https://www.youtube.com/watch?v=BsavoQWAVqM

**Comment by dotnetjunkie** [comment]
Hi @maulwuff,

That's a simple choice of convenience. This project is a reference architecture application that shows the concept of it and how messages flow through the system. Adding async/await would only complicate things in understanding what's going on, and besides, it depends on your application whether or not the use of async/await is beneficial. That's why this project doesn't add this extra noise. It is up to you, as developer and architect, to decide what's best for your application and change the abstractions accordingly.

**Comment by maulwuff** [comment]
thank you both
