### ISSUE TITLE
Rate-limiting

### ISSUE THREAD

**Issue by timohayes** [dotnetjunkie/solidservices#32]
I am using some of your command/query abstractions proposed in this reference architecture to great success - thanks very much for sharing this!

I have a question. I would like to introduce a way to rate-limit certain commands (purposely only allow a configurable rate of execution per command). For example, a command handler which uses an http client to invoke a sensitive API that limits how many requests per minute. I am wondering how you would suggest implementing this capability using an architecture very similar to your reference architecture?

I am considering using a decorator that would only be applied to certain command handlers, which is injected with a singleton manager of sorts that keeps track of the last time of execution, and would delay until the next interval. This doesn't seem very elegant, so I am hoping you have a better idea?

Thanks!

**Comment by dotnetjunkie** [comment]
I think there are two questions to ask here:

1. Where do you want the throttling to take place? Do you want to throttle (web) requests, or do you want the web requests to continue and succeed, while only throttling the underlying API?
2. What should the expected behavior be when a limit is reached? Should operations be blocked until the you go under the threshold again? Of do you want to cancel the operation. For instance, by returning a 503 (Service Unavailable) HTTP error code?

If you want the throttling to take place on the web request, a command-handler decorator would be an appropriate place to implement this logic. You can decide to simply block until the resource becomes available again, or directly throw an exception that can be translated to an HTTP error code by the stack above. Do note, however, that if requests keep coming in on a higher pace then the threshold, you will run out of threads soon, and this can bring the complete service down. Not only the execution of that single command.

A more obvious solution is to use some sort of queuing. Depending on your needs you can queue either commands or you queue domain events. With queuing you let commands be added to the queue in any possible pace, and without delays while, on the other hand, processing them at the rate you require. Queuing is an excellent place to apply throttling.

If you decide to use domain events, you can let your commands be executed synchronously (meaning: the client's web request blocks until the command has been processed). The command handlers of those synchronously executed commands can than publish events. Those events will be queued and executed asynchronously.

In the past I built systems with any combination of synchronicity and asynchronicity. For instance, I've helped build an application that processed both commands and events asynchronously from a queue, and applied throttling to some of the events. Throttling was required in our case, because the system had monthly "bursts" of a few million messages (published at the same moment), while information had to be pushed to (among other things) a back-end CRM system that couldn't handle a load higher than a few requests per second.

If you decide to go with queuing, however, the question now becomes, what to use for implementing queuing. I used a myriad of solutions in the past, ranging from writing JSON files to directory on disk, from self-implemented SQL Server tables serving as queue, to queuing systems like RabbitMQ (in combination with frameworks such as MassTransit or NServiceBus).

**Comment by timohayes** [comment]
Thanks Steven, your answer was very helpful, as always. As I am in fact using domain events, I went with the synchronous command handler decorator and async event processing.
