### ISSUE TITLE
Query Pattern and loading navigation properties

### ISSUE THREAD

**Issue by boomtopper** [dotnetjunkie/solidservices#7]
Hi Steven,

I'm responding to your email as you asked to to post the details here as an issue. Here is the code that I have so far, sorry it's VB.NET I have to do it for work, but it shouldn't be too hard to read. The ORM I'm using is entity framework.

Here is my base abstract class that represents a query pattern that I then inherit from for each type of query.

```vb.net
Public MustInherit Class QueryBase(Of TResult As Class)

    Protected ReadOnly DBContext As Data.ApplicationDBContext

    Protected Sub New(context As Data.ApplicationDBContext)
        DBContext = context
    End Sub

    Public MustOverride Function Retrieve() As TResult
End Class
```

Here is a simple example of a query. Not that it is eagerly loading related data every time.
```vb.net
Public Class GetProcedureTemplateHeaderQuery
    Inherits QueryBase(Of ProcedureTemplateHeader)

    Public Property TemplateId As Integer

    Public Sub New(context As ApplicationDBContext)
        MyBase.New(context)
    End Sub

    Public Overrides Function Retrieve() As ProcedureTemplateHeader
        Return DBContext.ProcedureTemplateHeaders _
                .Include(Function(m) m.ProcedureTemplateStages.Select(Function(e) e.ProcedureTemplateDetails.Select(Function(d) d.ProcedureTemplateQuestions))) _
                .Include(Function(c) c.ProcedureTemplateStages.Select(Function(a) a.ProcedureTemplateDetails.Select(Function(b) b.ProcedureTemplateGrouping))) _
                .SingleOrDefault(Function(m) m.Id = TemplateId)
    End Function
End Class
```

Here is my ProcedureTemplateHeader entity. A Template Header is made up of many stages and those stages are each made up of many details.

```vb.net
Public Class ProcedureTemplateHeader
    <Key>
    Public Property Id As Integer

    <Required>
    <StringLength(255)>
    Public Property Name As String

    Public Property ProcedureTemplateStages As ICollection(Of ProcedureTemplateStage)

    Public Sub New()
        ProcedureTemplateStages = New HashSet(Of ProcedureTemplateStage)
    End Sub

End Class
```
```vb.net
Public Class ProcedureTemplateStage
    <Key>
    Public Property Id As Integer

    Public Property HeaderId As Integer
    <ForeignKey("HeaderId")>
    Public Property ProcedureTemplateHeader As ProcedureTemplateHeader

   'Other data

    Public Property ProcedureTemplateDetails As ICollection(Of ProcedureTemplateDetail)

    Public Sub New()
        ProcedureTemplateDetails = New HashSet(Of ProcedureTemplateDetail)
    End Sub
End Class
```

```vb.net
Public Class ProcedureTemplateDetail
    <Key>
    Public Property Id As Integer

    Public Property StageId As Integer
    <ForeignKey("StageId")>
    Public Property ProcedureTemplateStage As ProcedureTemplateStage

    ' Other data

    Public Property ProcedureTemplateQuestions As ICollection(Of ProcedureTemplateQuestion)
    Public Property ProcedureTemplateGrouping As ICollection(Of ProcedureTemplateDetailGroup)

    Public Sub New()
        ProcedureTemplateQuestions = New HashSet(Of ProcedureTemplateQuestion)
        ProcedureTemplateGrouping = New HashSet(Of ProcedureTemplateDetailGroup)
    End Sub
End Class
```

Here is how my query is then consumed in my controller
```vb.net
    Public Class TestController
        Inherits Controller

        ' GET: Test
        Function Index(id As Integer) As ActionResult
            Dim qry As New GetProcedureTemplateHeaderQuery(WebAppHelper.GetContext()) With {.TemplateId = id}
            Dim header = qry.Retrieve()

            'Do some work with my header

            Return View(header)
        End Function
    End Class
```

What I am curious about is that every time I use GetProcedureTemplateHeaderQuery's retrieve it will get all of the data associated and not just the header, the trouble with this is that the consumer might only need the header and not need to know about the stages and details of the stage. What is the best way of approaching this?

**Comment by dotnetjunkie** [comment]
First of all, the design around queries that you are using is _not_ the model I advocate on [my blog](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=92). You are putting data (query) and behavior (handler) in the same class and this leads to sort of problems, such as the inability to test consumers of those queries in isolation, and the inability to apply cross-cutting concerns around the execution of this behavior. You should seriously reconsider your design and take again a good look at what I'm proposing on my blog.

Second, as I see it, the problem you are having has nothing to do with the query model at all. It has to do with how you use Entity Framework and possibly how your entities are consumed by the MVC Razor view engine. I would typically advice _not_ to return entities from your queries _at all_, but instead define a DTO or view model specific for the given use case. This way the query handler has full control over the returned data and you can prevent data from being lazy loaded, and therefore prevent the [N+1 query problem](https://secure.phabricator.com/book/phabcontrib/article/n_plus_one/).

So if you keep having problems with the way how data is loaded, my advice is to post a question on Stackoverflow about this. Make sure to strip your example and remove all unneeded details; to me, your query implementation is an implementation detail, not relevant to your problem.

**Comment by boomtopper** [comment]
Ok I understand what you mean and have changed this to work like how you've set on your blog. Most of my views in MVC use a View Model which I then construct from the entities. These View Models exist in the web app project and you are saying that the query handlers should return those view models instead? This would mean I would have to move all my view models in to the business library?

**Comment by dotnetjunkie** [comment]
> These View Models exist in the web app project and you are saying that the query handlers should return those view models instead? This would mean I would have to move all my view models in to the business library?

Well, yes and no.

The data that query handlers produce is very _use case_ specific. So every use case in your system deserves its own specific query message, and the data that is returned should be tailored to that specific use case. This allows those queries to be tuned for that specific need/screen/page (and for instance allows you to grab all required data in one single query, removing the N+1 query problem). This would be much harder to do if you just return a generic block of data (like a group of entities with their navigation properties) and expect the view to pull out the data that suit its need. Let's for sake of argument call the objects returned from query handlers **DTO**s, to distinquish them from View Model objects defind in your Presentation Layer.

Having query-specific DTOs almost completely removes the need to have Presentation Layer specific View Model objects, since in the most case, the returned data can be used directly in the view. The view can therefore directly depend on those DTOs. You might still need View Models now and then, since sometimes you need to enrich the data returned from your Business Layer with Presentation specific data. These are things like URLs, or sometimes you wish to combine multiple sets of data into a single View Model. This can happen when you have a set of Form data with drop down lists. These might come from different sources, and you might want to combine them into a single View Model.

> This would mean I would have to move all my view models in to the business library?

I would say _no_ to this. Although you might _physically_ place those DTOs in the same project as your Business Layer is, _logically_ these DTOs are not part of your Business Layer. These objects define the contract between your Presentation Layer and Business Layer. You could extract those messages to their own project, while calling it _MyApp.Messages_ or _MyApp.Contracts_, but whether that is useful depends on your type of project. I place those DTOs in a _Contracts_ project, when I have a desktop or mobile client that needs to communicate with the server through using these DTOs, and where this client shouldn't take a dependency on the Business Layer (because of security reasons or simply because the client code isn't compatible with the code in the BL).

Since these DTOs are _not_ part of your Business Layer, it is fine for the view in your Presentation Layer to have a dependency on them. Both the Presentation Layer and the Business Layer have a dependency on your Contract 'layer', while those Contracts don't depend on anything else.

**Comment by boomtopper** [comment]
It's sounding like I create these DTOs and sometimes I could be use them directly as view models and if I want extra information I create view models which are composed of DTOs, such as for data sources for drop downs or for extra visual information to be presented? 

Does it then make sense to use command object DTOs in a view if there is no other data needed by the view?

**Comment by dotnetjunkie** [comment]
> It's sounding like I create these DTOs and sometimes I could be use them directly as view models and if I want extra information I create view models which are composed of DTOs, such as for data sources for drop downs or for extra visual information to be presented?

Exactly. Composition is key here.

> Does it then make sense to use command object DTOs in a view if there is no other data needed by the view?

Absolutely. What I do in my view is bind command properties directly to my Razor view, because when command properties are marked with DataAnnotation attributes, you get client-side validation for free. You could even create a View Model that wraps a command. This way when you post back the View Model, you can simply get the command out of the VM and pass it through to your command handler.

**Comment by boomtopper** [comment]
Hi Steven,

This is what I've come up with to solve the loading of related entities and just wanted to check I'm in the right direction. 

I have created a query handler that represents the view I am interested in.
```vb.net
Public Class GetProcedureTemplateForEditHandler
    Implements IQueryHandler(Of GetProcedureTemplateForEditQuery, ProcedureTemplateForEditResult)

    Private _context As Data.ApplicationDBContext
    Private _headerHandler As IQueryHandler(Of GetProcedureTemplateHeaderQuery, ProcedureTemplateHeaderResult)
    Private _stagesHandler As IQueryHandler(Of GetProcedureTemplateStagesQuery, List(Of ProcedureTemplateStageResult))

    Public Sub New(context As Data.ApplicationDBContext,
                   headerHandler As IQueryHandler(Of GetProcedureTemplateHeaderQuery, ProcedureTemplateHeaderResult),
                   stagesHandler As IQueryHandler(Of GetProcedureTemplateStagesQuery, List(Of ProcedureTemplateStageResult)))
        _context = context
        _headerHandler = headerHandler
        _stagesHandler = stagesHandler
    End Sub

    Public Function Handle(query As GetProcedureTemplateForEditQuery) As ProcedureTemplateForEditResult Implements IQueryHandler(Of GetProcedureTemplateForEditQuery, ProcedureTemplateForEditResult).Handle
        Dim output As New ProcedureTemplateForEditResult
        output.Template = _headerHandler.Handle(New GetProcedureTemplateHeaderQuery With {.TemplateId = query.TemplateId})
        output.Template.ProcedureTemplateStages = _stagesHandler.Handle(New GetProcedureTemplateStagesQuery With {.HeaderId = query.TemplateId})
        Return output
    End Function
End Class
```

Here is the query parameters
```vb.net
Public Class GetProcedureTemplateForEditQuery
    Implements IQuery(Of ProcedureTemplateForEditResult)

    Public Property TemplateId As Integer
    Public Property StageNum As Integer
End Class
```

Here is the query result
```vb.net
Public Class ProcedureTemplateForEditResult
    Public Property Template As ProcedureTemplateHeaderResult

    'Below data to be filled when fully implemented
    'Public Property CurrentStageIdx As Integer
    'Public Property NextStageIdx As Integer?
End Class
```

Hopefully you can guess how the other queries work as they are quite simple. The idea is that This query uses your simple injection to inject the handlers it needs and then use them for the data it needs.

Let me know what you think? 
Thanks

**Comment by dotnetjunkie** [comment]
Looks good to me.
